apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# configurations:


namespace: cluster-a-policies
nameSuffix: -cluster-a

helmGlobals:
  chartHome: ../../policies

resources:
  - ../../policies/base/

helmCharts:
  - releaseName: pone
    name: policyone
    valuesFile: values.yaml

  - releaseName: ptwo
    name: policytwo
    valuesFile: values.yaml
