apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - generator1.yml
  - generator2.yml

labels:
- includeSelectors: true
  pairs:
    opens-cluster-management.io/policy-set: openshift-plus